### ISSUE TITLE
Allergy Icons

### ISSUE THREAD

**Issue by nickleman** [arsaboo/homeassistant-config#21]
Can you share the local icons you use for the pollen and cold-flu sensor displays?

**Comment by arsaboo** [comment]
Will share them soon once I clean up my icon folder.

**Comment by FireBall1725** [comment]
+1

**Comment by christianlappin** [comment]
+1

**Comment by FireBall1725** [comment]
So since I couldn't find anything else that would work, and I didn't want to wait I took a stab at making something, I think it came out alright.

![image](https://user-images.githubusercontent.com/727458/62002206-1e45bf00-b0b4-11e9-9ece-560eee7b7d96.png)

![low](https://user-images.githubusercontent.com/727458/62002183-d3c44280-b0b3-11e9-8799-12f98f49c23f.png)
![low-medium](https://user-images.githubusercontent.com/727458/62002182-d32bac00-b0b3-11e9-8028-03d8334e0cb9.png)
![medium](https://user-images.githubusercontent.com/727458/62002185-d3c44280-b0b3-11e9-8bf5-3a1f8d2f4fa6.png)
![medium-high](https://user-images.githubusercontent.com/727458/62002184-d3c44280-b0b3-11e9-8ff6-b99caaa9507b.png)
![high](https://user-images.githubusercontent.com/727458/62002181-d32bac00-b0b3-11e9-9bee-73f62e6d97e9.png)

**Comment by nickleman** [comment]
I think they came out great. Thanks for sharing them.

**Comment by christianlappin** [comment]
These are awesome @FireBall1725 !! Thanks for making and sharing!

**Comment by arsaboo** [comment]
@FireBall1725 Thanks for sharing. Here are the icons that I am using:
![high](https://user-images.githubusercontent.com/18319734/78695708-6fa57f80-78cc-11ea-8020-a82512930780.png)
![low](https://user-images.githubusercontent.com/18319734/78695712-703e1600-78cc-11ea-8b9f-8e1237612097.png)
![low-medium](https://user-images.githubusercontent.com/18319734/78695714-703e1600-78cc-11ea-98f3-7db979037e65.png)
![medium](https://user-images.githubusercontent.com/18319734/78695716-703e1600-78cc-11ea-9245-ef0c4c54b42f.png)
![medium-high](https://user-images.githubusercontent.com/18319734/78695719-70d6ac80-78cc-11ea-9079-92bd3158ac1f.png)
